export const demoData = {
  sheets: [
    { label: "January", netIncome: 7200, userId: 8 },
    { label: "February", netIncome: 6400, userId: 8 },
    { label: "March", netIncome: 8100, userId: 8 },
    { label: "April", netIncome: 5600, userId: 8 },
    { label: "May", netIncome: 9300, userId: 8 },
    { label: "June", netIncome: 7800, userId: 8 }
  ],

  expenses: [

    // January (sheetId: 1)
    { name: "Rent", amount: 1400, isPaid: true, sheetId: 1 },
    { name: "Groceries", amount: 320, isPaid: true, sheetId: 1 },
    { name: "Internet", amount: 85, isPaid: true, sheetId: 1 },
    { name: "Electric Bill", amount: 110, isPaid: false, sheetId: 1 },
    { name: "Gas", amount: 90, isPaid: true, sheetId: 1 },
    { name: "Phone Bill", amount: 95, isPaid: true, sheetId: 1 },
    { name: "Netflix", amount: 16, isPaid: true, sheetId: 1 },
    { name: "Spotify", amount: 11, isPaid: true, sheetId: 1 },
    { name: "Gym Membership", amount: 55, isPaid: false, sheetId: 1 },
    { name: "Car Insurance", amount: 140, isPaid: true, sheetId: 1 },
    { name: "Coffee", amount: 45, isPaid: true, sheetId: 1 },
    { name: "Dining Out", amount: 120, isPaid: false, sheetId: 1 },
    { name: "Parking", amount: 35, isPaid: true, sheetId: 1 },
    { name: "Laundry", amount: 22, isPaid: true, sheetId: 1 },
    { name: "Amazon Purchase", amount: 75, isPaid: false, sheetId: 1 },

    // February (sheetId: 2)
    { name: "Rent", amount: 1400, isPaid: true, sheetId: 2 },
    { name: "Groceries", amount: 310, isPaid: true, sheetId: 2 },
    { name: "Internet", amount: 85, isPaid: true, sheetId: 2 },
    { name: "Electric Bill", amount: 95, isPaid: true, sheetId: 2 },
    { name: "Gas", amount: 80, isPaid: false, sheetId: 2 },
    { name: "Phone Bill", amount: 95, isPaid: true, sheetId: 2 },
    { name: "Netflix", amount: 16, isPaid: true, sheetId: 2 },
    { name: "Spotify", amount: 11, isPaid: true, sheetId: 2 },
    { name: "Gym Membership", amount: 55, isPaid: true, sheetId: 2 },
    { name: "Car Insurance", amount: 140, isPaid: true, sheetId: 2 },
    { name: "Coffee", amount: 50, isPaid: false, sheetId: 2 },
    { name: "Dining Out", amount: 135, isPaid: true, sheetId: 2 },
    { name: "Parking", amount: 30, isPaid: true, sheetId: 2 },
    { name: "Laundry", amount: 20, isPaid: false, sheetId: 2 },
    { name: "Clothing", amount: 120, isPaid: true, sheetId: 2 },

    // March (sheetId: 3)
    { name: "Rent", amount: 1400, isPaid: true, sheetId: 3 },
    { name: "Groceries", amount: 340, isPaid: true, sheetId: 3 },
    { name: "Internet", amount: 85, isPaid: true, sheetId: 3 },
    { name: "Electric Bill", amount: 105, isPaid: false, sheetId: 3 },
    { name: "Gas", amount: 95, isPaid: true, sheetId: 3 },
    { name: "Phone Bill", amount: 95, isPaid: true, sheetId: 3 },
    { name: "Netflix", amount: 16, isPaid: true, sheetId: 3 },
    { name: "Spotify", amount: 11, isPaid: true, sheetId: 3 },
    { name: "Gym Membership", amount: 55, isPaid: false, sheetId: 3 },
    { name: "Car Insurance", amount: 140, isPaid: true, sheetId: 3 },
    { name: "Coffee", amount: 60, isPaid: true, sheetId: 3 },
    { name: "Dining Out", amount: 150, isPaid: false, sheetId: 3 },
    { name: "Parking", amount: 40, isPaid: true, sheetId: 3 },
    { name: "Laundry", amount: 24, isPaid: true, sheetId: 3 },
    { name: "Video Game", amount: 70, isPaid: false, sheetId: 3 },

    // April (sheetId: 4)
    { name: "Rent", amount: 1400, isPaid: true, sheetId: 4 },
    { name: "Groceries", amount: 300, isPaid: true, sheetId: 4 },
    { name: "Internet", amount: 85, isPaid: true, sheetId: 4 },
    { name: "Electric Bill", amount: 120, isPaid: false, sheetId: 4 },
    { name: "Gas", amount: 85, isPaid: true, sheetId: 4 },
    { name: "Phone Bill", amount: 95, isPaid: true, sheetId: 4 },
    { name: "Netflix", amount: 16, isPaid: true, sheetId: 4 },
    { name: "Spotify", amount: 11, isPaid: true, sheetId: 4 },
    { name: "Gym Membership", amount: 55, isPaid: true, sheetId: 4 },
    { name: "Car Insurance", amount: 140, isPaid: true, sheetId: 4 },
    { name: "Coffee", amount: 40, isPaid: false, sheetId: 4 },
    { name: "Dining Out", amount: 110, isPaid: true, sheetId: 4 },
    { name: "Parking", amount: 32, isPaid: true, sheetId: 4 },
    { name: "Laundry", amount: 18, isPaid: true, sheetId: 4 },
    { name: "Home Supplies", amount: 90, isPaid: false, sheetId: 4 },

    // May (sheetId: 5)
    { name: "Rent", amount: 1400, isPaid: true, sheetId: 5 },
    { name: "Groceries", amount: 350, isPaid: true, sheetId: 5 },
    { name: "Internet", amount: 85, isPaid: true, sheetId: 5 },
    { name: "Electric Bill", amount: 130, isPaid: true, sheetId: 5 },
    { name: "Gas", amount: 100, isPaid: false, sheetId: 5 },
    { name: "Phone Bill", amount: 95, isPaid: true, sheetId: 5 },
    { name: "Netflix", amount: 16, isPaid: true, sheetId: 5 },
    { name: "Spotify", amount: 11, isPaid: true, sheetId: 5 },
    { name: "Gym Membership", amount: 55, isPaid: true, sheetId: 5 },
    { name: "Car Insurance", amount: 140, isPaid: true, sheetId: 5 },
    { name: "Coffee", amount: 65, isPaid: false, sheetId: 5 },
    { name: "Dining Out", amount: 160, isPaid: true, sheetId: 5 },
    { name: "Parking", amount: 36, isPaid: true, sheetId: 5 },
    { name: "Laundry", amount: 25, isPaid: false, sheetId: 5 },
    { name: "Concert Ticket", amount: 120, isPaid: true, sheetId: 5 },

    // June (sheetId: 6)
    { name: "Rent", amount: 1400, isPaid: true, sheetId: 6 },
    { name: "Groceries", amount: 330, isPaid: true, sheetId: 6 },
    { name: "Internet", amount: 85, isPaid: true, sheetId: 6 },
    { name: "Electric Bill", amount: 125, isPaid: false, sheetId: 6 },
    { name: "Gas", amount: 95, isPaid: true, sheetId: 6 },
    { name: "Phone Bill", amount: 95, isPaid: true, sheetId: 6 },
    { name: "Netflix", amount: 16, isPaid: true, sheetId: 6 },
    { name: "Spotify", amount: 11, isPaid: true, sheetId: 6 },
    { name: "Gym Membership", amount: 55, isPaid: true, sheetId: 6 },
    { name: "Car Insurance", amount: 140, isPaid: true, sheetId: 6 },
    { name: "Coffee", amount: 48, isPaid: false, sheetId: 6 },
    { name: "Dining Out", amount: 140, isPaid: true, sheetId: 6 },
    { name: "Parking", amount: 34, isPaid: true, sheetId: 6 },
    { name: "Laundry", amount: 21, isPaid: true, sheetId: 6 },
    { name: "Streaming Add-On", amount: 9, isPaid: false, sheetId: 6 }
  ]
};